version: '3.4'
services:
  consul:
    image: consul
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'       
    volumes:
      - "C:/WORK/Sync/!Projects - Repo/Consul-Fabio-Demo/docker/consul/:/consul/config/"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
  fabio:
    image: fabiolb/fabio
    ports:
    - "9999:9999"
    - "9998:9998"
    volumes:
<<<<<<< HEAD
    - c:/Work/repo/Github/Consul-Fabio-Demo/docker/fabio.properties:/etc/fabio/fabio.properties"
=======
    - "C:/WORK/Sync/!Projects - Repo/Consul-Fabio-Demo/docker/fabio/fabio.properties:/etc/fabio/fabio.properties"
>>>>>>> 6960f053bb7504e05a21c2c06a563dce5cda4a63
    depends_on:
      - consul
    links:
      - consul 